### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by RichardLitt** [Seanmcn/citeproc-json#1]
Hey Sean, curious how you are using this on the front end. Doesn't citeproc-js need a server to run?

**Comment by seanmcn** [comment]
Hey Richard, I'm using PHP to create the citation data, but you could use Javascript either, its just an array like so: 

```
$citation = array();
$citation[$id]["id"] = $id;
$citation[$id]["type"][] = $type;
$citation[$id]["title"] = $title;
$citation[$id]["publisher"] =  $publisher
$citation[$id]["source"] = $source
$citation[$id]["author"][] = $author;
$citation[$id]["URL"] = $url
$citation[$id]["note"] = $notes;
$citation[$id]["rights"] = $rights;
$citation[$id]["language"] = $language;

```

Here is an example of basic usage Javscript wise;  [Gist](https://gist.github.com/Seanmcn/935c30eb42c84368feca) . 

Html wise I just have a dropdown of csl schemes with the values being the filenames, and an area for the citations to load.

**Comment by RichardLitt** [comment]
Hmm, I see. Thanks!
